
/*DROP DATABASE videoclub;*/


-- MySQL Script generated by MySQL Workbench
-- Tue 26 Nov 2019 03:18:10 PM -04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema VideoClub
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema VideoClub
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `VideoClub` DEFAULT CHARACTER SET utf8 ;
USE `VideoClub` ;

-- -----------------------------------------------------
-- Table `VideoClub`.`Pelicula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VideoClub`.`Pelicula` (
  `idPelicula` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `fechaLanzamiento` DATE NULL,
  `cantidadEjemplares` INT NULL,
  `precioActual` DECIMAL(10,4) NULL,
  PRIMARY KEY (`idPelicula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VideoClub`.`Nacionalidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VideoClub`.`Nacionalidad` (
  `idNacionalidad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idNacionalidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VideoClub`.`Productor`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `VideoClub`.`Productor` (
  `idProductor` INT NOT NULL auto_increment,
  `nombre` VARCHAR(100) NULL,
  `apellido` VARCHAR(100) NULL,
  `Nacionalidad_idNacionalidad` INT NOT NULL,
  PRIMARY KEY (`idProductor`, `Nacionalidad_idNacionalidad`),
  INDEX `fk_Productor_Nacionalidad1_idx` (`Nacionalidad_idNacionalidad` ASC),
  CONSTRAINT `fk_Productor_Nacionalidad1`
    FOREIGN KEY (`Nacionalidad_idNacionalidad`)
    REFERENCES `VideoClub`.`Nacionalidad` (`idNacionalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VideoClub`.`Actor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VideoClub`.`Actor` (
  `idActor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `sexo` CHAR(1) NULL,
  `apellido` VARCHAR(45) NULL,
  `Nacionalidad_idNacionalidad` INT NOT NULL,
  PRIMARY KEY (`idActor`, `Nacionalidad_idNacionalidad`),
  INDEX `fk_Actor_Nacionalidad1_idx` (`Nacionalidad_idNacionalidad` ASC),
  CONSTRAINT `fk_Actor_Nacionalidad1`
    FOREIGN KEY (`Nacionalidad_idNacionalidad`)
    REFERENCES `VideoClub`.`Nacionalidad` (`idNacionalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VideoClub`.`table1`
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `VideoClub`.`Socio`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `VideoClub`.`Socio` (
  `idSocio` INT NOT NULL AUTO_INCREMENT,
  `nombreSocio` VARCHAR(100) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `dni` CHAR(13) NOT NULL,
  `idSocioGarante` INT ,
  `apellido` VARCHAR(100) NULL,
  PRIMARY KEY (`idSocio`),
  INDEX `fk_Socio_Socio1_idx` (`idSocioGarante` ASC),
  CONSTRAINT `fk_Socio_Socio1`
    FOREIGN KEY (`idSocioGarante`)
    REFERENCES `VideoClub`.`Socio` (`idSocio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VideoClub`.`Director`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VideoClub`.`Director` (
  `nombre` VARCHAR(100) NOT NULL,
  `idDirector` INT NOT NULL AUTO_INCREMENT,
  `apellido` VARCHAR(100) NULL,
  `idNacionalidad` INT NOT NULL,
  PRIMARY KEY (`idDirector`),
  INDEX `fk_Director_Nacionalidad1_idx` (`idNacionalidad` ASC),
  CONSTRAINT `fk_Director_Nacionalidad1`
    FOREIGN KEY (`idNacionalidad`)
    REFERENCES `VideoClub`.`Nacionalidad` (`idNacionalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VideoClub`.`Ejemplar`
-- -----------------------------------------------------


-- -----------------------------------------------------
-- Table `VideoClub`.`Alquiler`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VideoClub`.`Alquiler` (
  `idAlquiler` INT NOT NULL AUTO_INCREMENT,
  `fechaInicial` DATE NOT NULL,
  `fechaFinal` DATE NOT NULL,
  `idSocio` INT NOT NULL,
  `idPelicula` INT NOT NULL,
  `numEjemplares` INT NULL check( `numEjemplares`>=1 and`numEjemplares`<4),
  `precioPorDia` DECIMAL(10,4) NULL,
  PRIMARY KEY (`idAlquiler`),
  INDEX `fk_Alquiler_Socio1_idx` (`idSocio` ASC),
  INDEX `fk_Alquiler_Pelicula1_idx` (`idPelicula` ASC),
  CONSTRAINT `fk_Alquiler_Socio1`
    FOREIGN KEY (`idSocio`)
    REFERENCES `VideoClub`.`Socio` (`idSocio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alquiler_Pelicula1`
    FOREIGN KEY (`idPelicula`)
    REFERENCES `VideoClub`.`Pelicula` (`idPelicula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VideoClub`.`Pelicula_has_Actor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VideoClub`.`Pelicula_has_Actor` (
  `Pelicula_idPelicula` INT NOT NULL,
  `Actor_idActor` INT NOT NULL,
  `esPrincipal` TINYINT(1) NULL,
  PRIMARY KEY (`Pelicula_idPelicula`, `Actor_idActor`),
  INDEX `fk_Pelicula_has_Actor_Actor1_idx` (`Actor_idActor` ASC),
  INDEX `fk_Pelicula_has_Actor_Pelicula1_idx` (`Pelicula_idPelicula` ASC),
  CONSTRAINT `fk_Pelicula_has_Actor_Pelicula1`
    FOREIGN KEY (`Pelicula_idPelicula`)
    REFERENCES `VideoClub`.`Pelicula` (`idPelicula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pelicula_has_Actor_Actor1`
    FOREIGN KEY (`Actor_idActor`)
    REFERENCES `VideoClub`.`Actor` (`idActor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VideoClub`.`Pelicula_has_Productor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VideoClub`.`Pelicula_has_Productor` (
  `Pelicula_idPelicula` INT NOT NULL,
  `Productor_idProductor` INT NOT NULL,
  PRIMARY KEY (`Pelicula_idPelicula`, `Productor_idProductor`),
  INDEX `fk_Pelicula_has_Productor_Productor1_idx` (`Productor_idProductor` ASC),
  INDEX `fk_Pelicula_has_Productor_Pelicula1_idx` (`Pelicula_idPelicula` ASC),
  CONSTRAINT `fk_Pelicula_has_Productor_Pelicula1`
    FOREIGN KEY (`Pelicula_idPelicula`)
    REFERENCES `VideoClub`.`Pelicula` (`idPelicula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pelicula_has_Productor_Productor1`
    FOREIGN KEY (`Productor_idProductor`)
    REFERENCES `VideoClub`.`Productor` (`idProductor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VideoClub`.`Pelicula_has_Director`
-- -----------------------------------------------------



-- -----------------------------------------------------
-- Table `VideoClub`.`TelefonoSocio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VideoClub`.`TelefonoSocio` (
  `Socio_idSocio` INT NOT NULL,
  `numeroTelefono` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Socio_idSocio`, `numeroTelefono`),
  CONSTRAINT `fk_TelefonoSocio_Socio1`
    FOREIGN KEY (`Socio_idSocio`)
    REFERENCES `VideoClub`.`Socio` (`idSocio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VideoClub`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VideoClub`.`Categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `nombreCategoria` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VideoClub`.`Pelicula_has_Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VideoClub`.`Pelicula_has_Categoria` (
  `Pelicula_idPelicula` INT NOT NULL,
  `Categoria_idCategoria` INT NOT NULL,
  PRIMARY KEY (`Pelicula_idPelicula`, `Categoria_idCategoria`),
  INDEX `fk_Pelicula_has_Categoria_Categoria1_idx` (`Categoria_idCategoria` ASC),
  INDEX `fk_Pelicula_has_Categoria_Pelicula1_idx` (`Pelicula_idPelicula` ASC),
  CONSTRAINT `fk_Pelicula_has_Categoria_Pelicula1`
    FOREIGN KEY (`Pelicula_idPelicula`)
    REFERENCES `VideoClub`.`Pelicula` (`idPelicula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pelicula_has_Categoria_Categoria1`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `VideoClub`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VideoClub`.`Pelicula_has_Nacionalidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VideoClub`.`Pelicula_has_Nacionalidad` (
  `Pelicula_idPelicula` INT NOT NULL,
  `Nacionalidad_idNacionalidad` INT NOT NULL,
  PRIMARY KEY (`Pelicula_idPelicula`, `Nacionalidad_idNacionalidad`),
  INDEX `fk_Pelicula_has_Nacionalidad_Nacionalidad1_idx` (`Nacionalidad_idNacionalidad` ASC),
  INDEX `fk_Pelicula_has_Nacionalidad_Pelicula1_idx` (`Pelicula_idPelicula` ASC),
  CONSTRAINT `fk_Pelicula_has_Nacionalidad_Pelicula1`
    FOREIGN KEY (`Pelicula_idPelicula`)
    REFERENCES `VideoClub`.`Pelicula` (`idPelicula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pelicula_has_Nacionalidad_Nacionalidad1`
    FOREIGN KEY (`Nacionalidad_idNacionalidad`)
    REFERENCES `VideoClub`.`Nacionalidad` (`idNacionalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VideoClub`.`Pelicula_has_Director1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VideoClub`.`Pelicula_has_Director1` (
  `Pelicula_idPelicula` INT NOT NULL,
  `Director_idDirector` INT NOT NULL,
  PRIMARY KEY (`Pelicula_idPelicula`, `Director_idDirector`),
  INDEX `fk_Pelicula_has_Director1_Director1_idx` (`Director_idDirector` ASC),
  INDEX `fk_Pelicula_has_Director1_Pelicula1_idx` (`Pelicula_idPelicula` ASC),
  CONSTRAINT `fk_Pelicula_has_Director1_Pelicula1`
    FOREIGN KEY (`Pelicula_idPelicula`)
    REFERENCES `VideoClub`.`Pelicula` (`idPelicula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pelicula_has_Director1_Director1`
    FOREIGN KEY (`Director_idDirector`)
    REFERENCES `VideoClub`.`Director` (`idDirector`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
